### ISSUE TITLE
PM2 ÖVÜLECEK BİR ŞEY DEĞİL

### ISSUE THREAD

**Issue by sydraxyz** [ByWest/west-bots-v13#1]
PM2 ÖVÜLECEK BİR ŞEY DEĞİL ŞUNU KAFANIZA SOKUN SADECE BİR MODÜL BU KADAR BASİT ADAMLAR SADECE SİTEDE BİLE NASIL YAPACAĞINIZI BELİRTMİŞ YOK PM2 YOK PM2 PM2 NE EZİK ADAMLARSINIZ YAQU GHWEGYUIQGYIWUEQW

**Comment by ByWest** [comment]
Kimse pm2 ile övünmüyor akıllı kardeşim. Paylaşacağım sistemin pm2 li olduğunu ve pm2 ile çalışan botların nasıl yapıldığı hakkında insanlara fikir vermesi açısından belirttim. Pm2 ve v13 kullanılarak yapılmıştır yazdım diye bu kadar kudurman saçma aptal seni

**Comment by Midwestxrd** [comment]
> PM2 ÖVÜLECEK BİR ŞEY DEĞİL ŞUNU KAFANIZA SOKUN SADECE BİR MODÜL BU KADAR BASİT ADAMLAR SADECE SİTEDE BİLE NASIL YAPACAĞINIZI BELİRTMİŞ YOK PM2 YOK PM2 PM2 NE EZİK ADAMLARSINIZ YAQU GHWEGYUIQGYIWUEQW

Kimse pm2 ile övünmüyor akıllı kardeşim. Paylaşacağım sistemin pm2 li olduğunu ve pm2 ile çalışan botların nasıl yapıldığı hakkında insanlara fikir vermesi açısından belirttim. Pm2 ve v13 kullanılarak yapılmıştır yazdım diye bu kadar kudurman saçma aptal seni

**Comment by sydraxyz** [comment]
KANKA BAŞLIĞA BİLE KOS KOCAMAN PM2 YAZMIŞSIN SADECE YÖNETİM MODÜLÜ BELKİDE İÇERİSİNDEKİ OLAYI BİLE BİLMEDEN SADECE ECOCONFİG İLE ÇALIŞTIRMAYI BİLİYORSUN QHIWEIHQWIHOEQW TAMAM SUSTUM CNM
